version: "3.8"

services:
  postgres:
    container_name: postgres-sql-sbn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book-social-network
    volumes:
      - postgres:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  bsn-ui:
    container_name: bsn-ui
    image: bsn/fronted:1.0.0
    ports:
      - "8080:80"
    networks:
      - spring-demo
    depends_on:
      - bsn-api
  bsn-api:
    container_name: bsn-api
    image: bsn/backend:1.0.4
    ports:
      - "8090:8090"
    networks:
      - spring-demo
    depends_on:
      - postgres
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
