version: "3.8"

services:
  postgres:
    container_name: postgres-sql-sbn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book-social-network
    volumes:
      - postgres:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  bsn-api:
    container_name: backend-api-bsn
    image: backend-api/backend-api:1.0.0
    ports:
      - "8080:8080"
    networks:
      - spring-demo
    depends_on:
      - postgres

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
