spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: yvhakizimana123@gmail.com
    password: oodfrvtulsshrbhg
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
      protocol: smtp

application:
  security:
    jwt:
      secret-key: BWgwvfUQbvfyhCHdIlcrFDn8/dAlonrY+Kj+DJ8mhSkkFl2v+XDv/M1KK9jWO+Bi0PF88wwTmkciUO3x7/d9Mqo/lv+5qk/Fz/YM97ylIEXhAz/e/1iPC95+f3UoyiIxTYf5z2vRfKu6twhjUwMZ+9eKiLfxqkHpOqAmWZhPSr2TRL+V91I303uyoYy7cU8LiX0LVkvXvTDX4vS7wdvGPvLIUxBzC1I/Ko6n+5oHNZm+bQhoph0SEHP8ne9n6EZQ8/sMJNs8wLX7qyuanD8KhkAnn+vFTu4PTzNnV+JwUGN1L87qRiZ7CIoNwasazvgu0rvFZH5g3Hx2kVRM82zznCmbWgYdCCR0vpR1Ourj23M=
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:8080/activate-account
  cors:
    origins: http://localhost:4200, http://localhost:8080
  file:
    uploads:
      photos-output-path: ./uploads
